[package]
name = "sled_nif"
version = "0.1.0-alpha"
authors = []
edition = "2018"

[lib]
name = "sled_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "^0.22.0-rc.0"
lazy_static = "^1.0"
sled = "^0.31"
