name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup rust
      uses: actions-rs/toolchain@v1.0.5
      with:
        default: true
        toolchain: stable
        profile: minimal
        components: rustfmt, clippy
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10.x'
        otp-version: '23.x'
    - name: Install Dependencies
      run: mix deps.get
    - name: Check Elixir Formatting
      run: mix format --check-formatted
    - name: Check Rust Formatting
      working-directory: "native/sled_nif"
      run: cargo fmt -- --check
    - name: Compile
      run: MIX_ENV=test mix compile --warnings-as-errors
    - name: Run Tests
      run: mix test
